### ISSUE TITLE
翻译错误回报

### ISSUE THREAD

**Issue by ReinforceZwei** [XIAYM-gh/Minecraft-Console-Client-ChineseTranslate#1]
https://github.com/XIAYM-gh/Minecraft-Console-Client-ChineseTranslate/blob/master/MinecraftClient/Settings.cs#L678

原句是`Prepend timestamps to chat messages`，翻译成`记录聊天时间戳`意思上会比较正确。

**Comment by XIAYM-gh** [comment]
好的XD
当初汉化时脑袋热了一下...
